name: Test Redis run

on:
  push:


jobs:
  test-ubuntu-jemalloc-arm64:
    runs-on: [Linux, ARM64]
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v3
      with:
        repository: redis/redis
    - name: make
      run: make REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: testprep
      run: sudo apt-get install tcl8.6 tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs ${{github.event.inputs.test_args}}
    - name: module api test
      run: ./runtest-moduleapi --verbose --dump-logs ${{github.event.inputs.test_args}}
    - name: sentinel tests
      run: ./runtest-sentinel ${{github.event.inputs.cluster_test_args}}
    - name: cluster tests
      run: ./runtest-cluster ${{github.event.inputs.cluster_test_args}}
    - name: unittest
      run: ./src/redis-server test all --accurate
